name = "cyberdudebivash-connect-hub"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

[assets]
directory = "./dist"

[vars]
PUBLIC_BRAND_NAME = "CYBERDUDEBIVASH Connect Hub"
PUBLIC_TAGLINE = "Connect. Protect. Grow."
PUBLIC_INTEL_API = "https://intel.cyberdudebivash.com"
PUBLIC_CONTACT_EMAIL = "contact@cyberdudebivash.in"
PUBLIC_SALES_EMAIL = "bivash@cyberdudebivash.com"
PUBLIC_PHONE = "+918179881447"
PUBLIC_WHATSAPP = "918179881447"
